//! Structured model manual; descriptive capability data, not a second contract.
pub fn descriptor() -> &'static str {
    r#"{
  "module":"Nib","descriptor_version":1,"transport_version":1,
  "purpose":"Immutable source-only vector geometry proposals",
  "scope":{"implemented":"two closed zero-handle axis-aligned rectangles","host_document_commit":"PENDING","native_ui":"PENDING","native_backend":"PENDING","native_integration":"PENDING","general_curve_parity":"PENDING"},
  "operations":["uniteCommand","backMinusFrontCommand","frontMinusBackCommand"],
  "operand_order":{"array":"not authoritative","z_order":"explicit bottom-to-top SVPT identities"},
  "options":{"precision":"finite positive pt","remove_redundant_points":false,"divide_and_outline_remove_unpainted":false,"loss_policy":"reject","result_mode":"proposal_only"},
  "input":{"path_schema":"hsk.studio.vector_path@1","canonical_required_fields":["schema_id","path_id","address","closed","anchors","winding_rule","fill_style_id"],"address":{"domain":"SLYR","property":"geometry","object_key":"nonempty ASCII alphanumeric, underscore or hyphen; at most128bytes"},"units":"pt","handles":"zero relative pt vectors","fill_style_id":"required present nullable SSTY","bytes":"original complete caller bytes; exact SHA256 and typed-value equality","strict_decode":["unknown fields rejected","duplicate fields rejected","missing fields rejected","invalid UTF8 or nonfinite numbers rejected","open geometry refused"]},
  "reads":["operand membership","current geometry bytes/hash and per-address revision","explicit z-order revision and identity order","caller-resolved PAINT styles including result style revision/fingerprint","target per-address revision","fresh cancel epoch"],
  "styles":{"authority":"caller resolution only","preservation":"explicit granted result SSTY PAINT stack","private_catalog":false},
  "provider":{"source":"Vectorcraft825d4fdb/linesweeper0.4.0 exact-axis source specialization; kurbo0.13.1 provenance","requested_heap_bytes":0,"storage":"fixed inline scratch and immutable Network","limits":{"source_edges":8,"pair_points":56,"cut_refs":128,"pieces":120,"vertices":64,"directed_endpoint_actions":240,"flat_loop_refs":120},"unavailable":["curves","epsilon perturbation","refit","sliver removal","automatic closure","grid or raster substitution"]},
  "topology":{"winding":"NONZERO","outer_orientation":"positive mathematical signed shoelace","holes":"negative mathematical signed shoelace","empty":"typed EmptyPathfinderResult","canonical":"positive zero, lexicographic vertices, least loop starts, ordered components/holes, deterministic segment indices","access":"borrowed immutable slices; absent straight-segment tangents"},
  "precision":{"effective_tolerance_pt":0,"maximum_error_pt":0,"exact":true,"geometry_loss":false,"style_loss":false,"meaning":"supported straight coordinates are selected from original endpoint/intersection coordinates; caller precision does not license geometric loss"},
  "budget":{"unit":"requested_owned_allocation_bytes","aggregate":"precharged unique caller inputs plus exact retained Arc layout; provider inline value already part of retained payload","includes":["owned requested capacities/layouts","control and ownership wrappers","simultaneous old/new allocations"],"excludes":["allocator bookkeeping","RSS"],"counters":"admitted pair contact points, admitted atomic endpoint actions, actual output counts and charged work; failures expose partial admitted counters","limits":"input_bytes operands anchors segments sweep_events intersections output_vertices output_segments output_regions output_loops work_units recursion_depth requested_allocation_bytes"},
  "lease":{"input":"verified caller preowned lifetime remains charged","output":"definite synchronous reservation before retained Arc allocation","clone":"shared retained allocation charged once until last reachable proposal/token drops","indeterminate":"proposal and reservation retained behind PendingToken","finalization":"caller exclusive context/sink boundary and final fresh read fence; no document mutation"},
  "diagnostics":{"port":"existing Observe SinkPort","wire":"HSKO closed geometry detail variant; see Observe descriptor for exact frame encoding","privacy":"stable IDs/address, closed code/disposition, revisions/epoch and bounded counters only; no path JSON, coordinates, private labels or raw text","delivery":"rejection/unavailable/indeterminate are explicit; no false accepted proposal"},
  "workflow":["own and charge immutable input/context lifetime","construct Request with original bytes and expected hashes/read revisions","prepare using ContextPort and AdmissionPort","inspect immutable Network and precision receipt","finalize under exclusive caller boundary","reconcile indeterminate delivery using fresh preowned Observe and diagnostic sink"],
  "consumer":{"entrypoint":"nib-consumer","descriptor":"--descriptor","run":"--operation uniteCommand|backMinusFrontCommand|frontMinusBackCommand --rects ax0 ay0 ax1 ay1 bx0 by0 bx1 by1 --path-a original-a.json --path-b original-b.json --execute","output":"source disposition, independently inspectable Network coordinates/loops, charged counts and captured Observe frame hex","fixture_scope":"local explicit caller context; no host or persisted document authority"},
  "argus":{"inspection":"public Network slices, precision receipt, actual bounded counts and independently decoded Observe frames","proof":"independent directed-loop closure, signed shoelace area, canonical ordering, result SSTY and retained retirement accounting","host_acceptance":"PENDING"},
  "recovery":{"stale":"refresh the complete caller read set and create a new proposal","budget":"increase explicit admissible limits or refuse","unsupported":"use a separately approved provider route; no silent fallback","delivery_rejected":"no source acceptance; release reachable owners normally","indeterminate":"retain token and reservation; reconcile without recomputing geometry or replaying delivery"}
}"#
}
