[package]
name = "hsk-studio-interop-psd"
version = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }

[features]
default = []

[lib]
path = "src/lib.rs"

[dependencies]
hsk-studio-accord = { path = "../hsk-studio-accord", version = "=0.1.0", default-features = false }
miniz_oxide = { version = "=0.9.1", default-features = false, features = ["with-alloc"] }

[[example]]
name = "interop-psd-consumer"
path = "examples/interop-psd-consumer.rs"
