/// Descriptive model navigation; canonical product requirements remain in the Master Spec.
pub fn descriptor() -> &'static str {
    r#"{
"module":"Type","descriptor_version":1,
"purpose":"Caller-granted immutable original-UTF8 positioned shaping proposals",
"entrypoints":{"prepare":"TextEngine::shaped_runs","inspect":"Prepared getters and coverage","finalize":"finalize","reconcile":"reconcile","diagnostics":"prepared_diagnostic, rejected_diagnostic, pending_diagnostic; shared Observe emit_shaping"},
"commands":{"compile":"cargo check --manifest-path handshake-studio-assets/Cargo.toml --locked --tests -p hsk-studio-type --no-default-features","owning_target":"foundation_contract","owning_filters":["mixed_script_bidi_font_runs","font_axis_missing_cancel_stale"],"runtime_executor":"independent validator; 60-second case limit","runtime_inputs":"Exact licensed fonts, independently produced pinned shaper reference and separate official bidi goldens; missing inputs refuse proof"},
"inputs":{"identity":"Existing SDOC,STXT,SLYR and STYS; no new durable identity","text":"Immutable original UTF8 plus full SHA256; preserve normalization only","readset":"Caller-granted property addresses, relevant revisions, fingerprints and complete resolved style inputs","target":"Existing STXT or SLYR ephemeral derived slot with exact revision/preimage","direction":"Distinct explicit story, paragraph and character override; unknown story requires explicit paragraphs","style":"Finite positive point size; explicit script and BCP47 language; ordered font resources; four-byte ASCII feature/axis tags","fonts":"Complete file SHA256, checked face index, resource/grant revisions and lifetime lease; no host discovery","limits":"Checked input/scalar/style/feature/axis/font/table/lookup/run/glyph/fallback/recursion/work/exact-byte/generation caps","actor":"Borrowed validated Accord actor, private correlation key and separate numeric Observe correlation"},
"selected_profile":{"shaper":"Private pinned Rustybuzz0.20.1 and ttf-parser0.25.1 native Rust adaptation","scripts":["Latn","Arab","Hani"],"common_resolution":"Zyyy requires one supported strong script within the shaping span; common-only input requires an explicit script","language":"Explicit caller BCP47, no locale guess","bidi":"Private unicode-bidi0.3.18 Unicode16, structured X6 overrides, original controls, L1 then L2","helper_versions":"ccc0.4.0/mirroring0.4.0 Unicode16; script0.5.8/properties0.1.4 Unicode17; exact semantics bound by COMPOSITION_VERSION","fallback":"Explicit candidate order, whole style/bidi span; no splitting combining/joining context into scalar fonts","flags":"MonotoneGraphemes, BOT|EOT|REMOVE_DEFAULT_IGNORABLES; no synthetic source controls","excluded_routes":"Unsupported profile refusal before unselected AAT/color/bitmap/SVG/CFF2/outline/legacy-kerning work"},
"outputs":{"paragraphs":"Original source order, one unwrapped preview line each","runs":"Unicode bidi visual order, original spans and font/axis/feature provenance","glyphs":"Actual directional shaper order; original source cluster endpoints; signed advances/offsets in points","conversion":"(f64(provider_value)*font_size_pt)/f64(provider_scale), no FMA/device rounding, positive zero","coverage":"Complete original byte partition: actual pre-delete shaped cluster groups, standalone nonrendering controls, paragraph separators","disposition":["shaped","empty_input","control_only"],"serialization":"Fixed composition-bound little-endian field/numeric order; sorted axis/feature provenance; no raw font or text bytes"},
"ownership":{"allocation":"Exact checked Layout admitted before allocation, simultaneous old/new growth charged, caller current-operation counters","borrowers":"InputLifetime plus font byte lease; borrower destroyed before lease","result":"Unique immutable admitted buffers and caller generation lease; no owned Clone or public charge reduction","pending":"Unique PendingToken retains full proposal/preimage/input lifetime and reservations until authoritative reconciliation"},
"caller_boundary":"FinalizationPort serializes fresh membership/readset/font/resolver/target/epoch verification with Observe delivery and intended-slot publication/ownership responsibility; definite failure preserves target, indeterminate prohibits blind retry",
"privacy":"Observe v5 receives stable authorized addresses, fixed code/disposition, bounded counts/revisions/epoch only; no raw text/font names/bytes/glyph coordinates/private labels/errors",
"inspection":"Public immutable positioned runs, source coverage, serialized bytes, Counts/Inspection and independently decoded shared Observe frame",
"recovery":{"stale":"Refresh relevant authoritative property/font/grant/epoch inputs and prepare again; unrelated document revision alone is not stale","budget":"Increase explicit permitted limits or refuse; no post-allocation admission","unsupported":"Use separately approved supported profile; do not clamp axes or invent glyph coverage","indeterminate":"Retain token and query exact prior result; never replay publication blindly"},
"pending":["independent source/runtime acceptance","full Type domain parity","container layout/linebreaking/outlines/rasterization","two-host positioned/raster parity","36-foundation barrier","Handshake host authorization/storage/undo/GUI adoption"]
}"#
}
