[package]
name = "hsk-studio-pulse"
version = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }

[features]
default = []

[dependencies]
hsk-studio-accord = { path = "../hsk-studio-accord", version = "=0.1.0", default-features = false }
hsk-studio-observe = { path = "../hsk-studio-observe", version = "=0.1.0", default-features = false }

[lib]
path = "src/lib.rs"

[[example]]
name = "pulse-consumer"
path = "examples/pulse-consumer.rs"
